### PR TITLE
Add basic parallel building to mymake via shell jobs system?

### PR DESCRIPTION
**Pull request by still-flow**
An attempt to speed up `mymake` builds a bit. Done via the possibly stupid (and probably not Windows-compatible) way of using the shell's job system. There was indeed some speedup locally for me, and here is the comparison of Github CI results:
- [serial mymake](https://github.com/rpljwi/hyperrogue/actions/runs/111604467)
- [parallel mymake](https://github.com/rpljwi/hyperrogue/actions/runs/111916309)

As you can see, overall run time went down somewhat. Of course, this will need further testing. Again, it's not up to me to decide whether it's worth it.

Oh, and there is no idiot check for `-j` parameter -- not sure if it's needed.

### CODE REVIEW

**Comment by Quuxplusone** [comment]
(Takes the CI build from 16 minutes to 12 minutes. Doesn't feel worth-it to me, FWIW.)
Yet a different approach would be to spin off each `system()` into its own `std::thread`. I wonder whether that would complexify or simplify the code, and how it would affect the running time.

**Comment by rpljwi** [comment]
Another approach could be to emit a Makefile and use `make`'s parallel build capability.

**Comment by rpljwi** [comment]
I think I like the delegation approach more; the code is quite simple. Here is the comparison (reusing entries from OP):
- [serial mymake](https://github.com/rpljwi/hyperrogue/actions/runs/111604467)
- [shell-parallelized mymake](https://github.com/rpljwi/hyperrogue/actions/runs/111916309)
- [make-parallelized mymake](https://github.com/rpljwi/hyperrogue/actions/runs/699029344)

The last two aren't exactly the same, since the very last entry uses `-j4` as opposed to `-j6`, but the time is even a bit better now.

I should probably close this PR and open one with that new approach, right?

**Comment by rpljwi** [comment]
As for threads, well, I have close to none experience programming with them, and I hear that their wrong usage can lead to some subtle bugs, so it's probably best left to someone else.

**Comment by rpljwi** [comment]
One last thing: on my system (4 cores) usual `mymake` takes around 5:50, and the one delegating to `make` (_not_ the one above -- haven't made the same comparison with that) takes only about 3:00. This is after running a couple of times.

**Comment by still-flow** [comment]
Closing this in favor of another approach. Will post a PR once that's in at least somewhat presentable state.

**Pull request closed without merging**
