### PR TITLE
Avoid casting to `unsigned char*` in color calculations.

### PR DESCRIPTION
**Pull request by Quuxplusone**
Fixes the same thing as #70, but in a different way.

### CODE REVIEW

**Comment by Quuxplusone** [comment]
@zenorogue ping? Any chance of getting something like this into master?

**Comment by zenorogue** [comment]
I like the lvalue approach much more than the getter/setter/switcher approach... so unless there is some serious problem with that, I would like to keep it. E.g., change it so that e.g. part(color, 0) returns the first byte on LE and the last byte on BE; or use a proxy class.

**Comment by Quuxplusone** [comment]
I would be happy to submit a patch that makes `part(c, i)` return a proxy class with an `operator=` so that the callsites could keep on using `part(c, i) = value`, but that seemed like a higher level of "C++ cleverness" than HyperRogue's normal level. I guess I should submit that PR and then we can compare that PR to this one (and to #70).

**Comment by zenorogue** [comment]
Oh, I did not notice #70 did use my first suggested method. Merged that, also included some of your suggestions. Thanks!

**Pull request closed without merging**
